### ISSUE TITLE
JsonFormats for classes with more than 15 parameters

### ISSUE THREAD

**Issue by jrudolph** [spray/spray-json#22]
https://groups.google.com/d/topic/spray-user/XR-lDyfEhII/discussion

**Comment by ShivanKaul** [comment]
I have a case class with 28 parameters (including nested case classes, so I *am* trying to reduce the number of parameters), and I'd like to be able to use spray-json elegantly in such cases. Is there no other option apart from writing custom + kludgy read/write methods?

Scala allowed >22 parameters for case classes since the discussion over here: https://github.com/spray/spray-json/issues/48
