### ISSUE TITLE
please explain bloom filter?

### ISSUE THREAD

**Issue by fommil** [spray/spray-json#233]
in this code https://github.com/spray/spray-json/blob/765c83248e0bbe867ddc9d479b4fe79493569a54/src/main/scala/spray/json/JsonParser.scala#L148-L156

```
  private def `char`() =
    // simple bloom-filter that quick-matches the most frequent case of characters that are ok to append
    // (it doesn't match control chars, EOI, '"', '?', '\', 'b' and certain higher, non-ASCII chars)
    if (((1L << cursorChar) & ((31 - cursorChar) >> 31) & 0x7ffffffbefffffffL) != 0L) appendSB(cursorChar)
    else cursorChar match {
      case '"' | EOI => false
      case '\\' => advance(); `escaped`()
      case c => (c >= ' ') && appendSB(c)
    }
```

maybe I'm being dumb, but doesn't the `>> 31` always set this to zero, or are you relying on `>>` bringing `1`s with it when the number is negative?

**Comment by fommil** [comment]
Also, the compiler warns about numeric widening, so in my fork I'm trying to convert things to `Long` where possible

**Comment by sirthias** [comment]
`(31 - cursorChar) >> 31` is branchless for `if (cursorChar > 31) 0xFFFFFFFF else 0`.

The `Long` variant would be `(31L - cursorChar) >> 63`.

**Comment by sirthias** [comment]
Actually, if you have the numeric widening warning on (as I do as well nowadays) the expression should be:

`((31 - cursorChar) >> 31).toLong` or `(31L - cursorChar.toLong) >> 63`.

It probably doesn't matter, which one you use, but the first one does the subtraction and the shift using only a 32bit register rather than a 64bit one, so technically it requires a tiny bit less resources. If you run in a 32bit JVM the effect will be more pronounced.

**Comment by sirthias** [comment]
Sorry, I forgot to explain the logic of the bloom filter:

The idea is to reduce the most common code path down to a single branch instruction. (The `match` in the `else` branch requires at least 5 comparisons for the common case.)

We do this by using the `cursorChar` value to index into a bit field and checking whether the respective bit is set. If it is we know that the character is good to append right away.

The single expression

```
((1L << cursorChar) & ((31 - cursorChar) >> 31) & 0x7ffffffbefffffffL) != 0L
```

is equivalent to this one:

```scala
if (cursorChar > 31) {
  val bitField = 0x7ffffffbefffffffL // has a 1-bit for every 'good' char
  val mask = 1L << cursorChar // select the right bit (loosing precision)
  (bitField & mask) != 0 // test whether the bit is set in the bitField
} else false
```

Since a `Long` can only hold 64 bits we can only distinguish 64 cases.
It's a bloom filter because the shift instruction (`<<`) only uses the lowest 6 bits of the `cursorChar` value and disregards all others. This means that all characters which have the same lowest 6 bits are mapped to the same bit in the bitField. So, if a bit is *not* set in the bitField, we still have to apply our regular tests to determine how to treat the character.
But the nice thing is, since most characters are ok, the bitField has a lot one 1-bits, which makes the bloom filter quite effective.

**Comment by fommil** [comment]
Ha! That's pretty awesome. Thanks for the explanation.
